// <auto-generated />
using Dictionary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace p3_C00445623_C00441253.Migrations
{
    [DbContext(typeof(DictionaryDbContext))]
    partial class DictionaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Dictionary.Dictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("definition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Definitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            definition = "A mischievous person",
                            word = "Rapscallion"
                        },
                        new
                        {
                            Id = 2,
                            definition = "A young and inexperienced person considered to be presumptuous or overconfident",
                            word = "Whippersnapper"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
